### ISSUE TITLE
Question about accuracy on testmini set of MathVista

### ISSUE THREAD

**Issue by FanqingM** [dle666/R-CoT#3]
Hi, Great work! I have some questions about this paper. Lokking forward to your reply!!
The code generate_response_geo_rcot8b.py only involves reasoning about geometry questions (a total of 208 questions), but the article shows that the accuracy rate on the testmini set of MathVista is 73.9. How are other questions tested?

**Comment by dle666** [comment]
Thank you for your interest, the results in the article are also the accuracy of solving geometry problems on the testmini set of MathVista, which we illustrate in the caption of Table 4.
<img width="602" alt="image" src="https://github.com/user-attachments/assets/c328d44a-25bf-4e07-90c8-f15bb10a99d3">

**Comment by dle666** [comment]
Feel free to reopen if necessary.
